// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV1gs78Y5Scmd_THH92EihurrywqKcJBA',
    appId: '1:536312548303:web:5e9ebdc19811433ba4a0ba',
    messagingSenderId: '536312548303',
    projectId: 'firestore-uygulamalari',
    authDomain: 'firestore-uygulamalari.firebaseapp.com',
    storageBucket: 'firestore-uygulamalari.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTAT0slxIbnw8x7oWjef47x8OGnn6zWQo',
    appId: '1:536312548303:android:85fca1b7e2d8f3f8a4a0ba',
    messagingSenderId: '536312548303',
    projectId: 'firestore-uygulamalari',
    storageBucket: 'firestore-uygulamalari.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3SzLbcmLzHuuc_OJ9kj4-LjHmoTHQGvU',
    appId: '1:536312548303:ios:23be3dfb50faf50da4a0ba',
    messagingSenderId: '536312548303',
    projectId: 'firestore-uygulamalari',
    storageBucket: 'firestore-uygulamalari.appspot.com',
    iosBundleId: 'com.example.firestoreEcommerceAdminpanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3SzLbcmLzHuuc_OJ9kj4-LjHmoTHQGvU',
    appId: '1:536312548303:ios:bffc778d424a67dca4a0ba',
    messagingSenderId: '536312548303',
    projectId: 'firestore-uygulamalari',
    storageBucket: 'firestore-uygulamalari.appspot.com',
    iosBundleId: 'com.example.firestoreEcommerceAdminpanel.RunnerTests',
  );
}
